const admin = [
  {
    key: '1',
    title: 'Dashboard',
    label: "Dashboard",
    label_key: "dashboard",
    icon: "TbLayoutDashboard",
    default_color_icon: '',
    path: "/admin/dashboard",
    path_active: "/admin/dashboard",
    path_list: [],
  },
  {
    key: '2',
    title: 'CCTV',
    label: 'CCTV',
    label_key: "cctv",
    icon: 'TbVideo',
    default_color_icon: '',
    path: "/admin/cctv",
    path_active: "/admin/cctv",
    path_list: [],
  },
  {
    key: '3',
    title: 'Analytic',
    label: 'Analytic',
    label_key: "analytic",
    icon: 'TbCar',
    default_color_icon: '',
    path: "/admin/analytic",
    path_active: "/admin/analytic",
    path_list: [],
  },
  {
    key: '4',
    title: 'Counting',
    label: 'Counting',
    label_key: "counting",
    icon: 'TbTruckDelivery',
    default_color_icon: '',
    path: "/admin/counting",
    path_active: "/admin/counting",
    path_list: [],
  },
  {
    key: '5',
    title: 'Traffic',
    label: 'Traffic',
    label_key: "traffic",
    icon: 'TbTrafficLights',
    default_color_icon: '',
    path: "/admin/traffic",
    path_active: "/admin/traffic",
    path_list: [],
  },
  {
    key: '6',
    title: 'Crosswalk',
    label: 'Crosswalk',
    label_key: "crosswalk",
    icon: "TbWalk",
    default_color_icon: '',
    path: "/admin/crosswalk",
    path_active: "/admin/crosswalk",
    path_list: [],
  },
  {
    key: '7',
    title: 'Lighting',
    label: 'Lighting',
    label_key: "lighting",
    icon: "TbBolt",
    default_color_icon: '',
    path: "/admin/lighting",
    path_active: "/admin/lighting",
    path_list: [],
  },
  {
    key: '14',
    title: 'Bridge Lighting',
    label: 'Bridge Lighting',
    label_key: "bridge-lighting",
    icon: "TbLamp",
    default_color_icon: '',
    path: "/admin/bridge-lighting",
    path_active: "/admin/bridge-lighting",
    path_list: [],
  },
  {
    key: '8',
    title: 'VMS',
    label: "VMS",
    label_key: "vms",
    icon: "TbDeviceDesktop",
    default_color_icon: '',
    path: "/admin/vms",
    path_active: "/admin/vms",
    path_list: [],
  },
  {
    key: '9',
    title: 'Tunnel',
    label: 'Tunnel',
    label_key: "tunnel",
    icon: "TbBuildingBridge",
    default_color_icon: '',
    path: "/admin/tunnel",
    path_active: "/admin/tunnel",
    path_list: [],
  },
  {
    key: '10',
    title: 'WIM',
    label: "WIM",
    label_key: "wim",
    icon: "TbBuildingBridge2",
    default_color_icon: '',
    path: "/admin/wim",
    path_active: "/admin/wim",
    path_list: [],
  },
  {
    key: '11',
    title: 'Tracking',
    label: "Tracking",
    label_key: "tracking",
    icon: "TbTopologyStar3",
    default_color_icon: '',
    path: "/admin/tracking",
    path_active: "/admin/tracking",
    path_list: [],
  },
  {
    key: '12',
    title: 'Settings',
    label: "Settings",
    label_key: "settings",
    icon: "TbAdjustmentsHorizontal",
    default_color_icon: '',
    path: "/admin/settings",
    path_active: "/admin/settings",
    path_list: [],
  },
  {
    key: '13',
    title: 'Monitoring',
    label: "Monitoring",
    label_key: "monitoring",
    icon: "TbBriefcase",
    default_color_icon: '',
    path: "/admin/monitoring",
    path_active: "/admin/monitoring",
    path_list: [],
  },
]

export default admin