export interface AdminMenuItem {
  key: string
  title: string
  label: string
  label_key: string
  icon: string
  default_color_icon: string
  path: string
  path_active: string
  path_list: string[]
}

const admin: AdminMenuItem[] = [
  {
    key: '1',
    title: 'Dashboard',
    label: "Dashboard",
    label_key: "dashboard",
    icon: "TbLayoutDashboard",
    default_color_icon: '',
    path: "/admin/dashboard",
    path_active: "/admin/dashboard",
    path_list: [],
  },
  {
    key: '2',
    title: 'CCTV',
    label: 'CCTV',
    label_key: "cctv",
    icon: 'TbVideo',
    default_color_icon: '',
    path: "/admin/cctv",
    path_active: "/admin/cctv",
    path_list: [],
  },
  {
    key: '3',
    title: 'Traffic Volume',
    label: 'Traffic Volume',
    label_key: "traffic_volume",
    icon: 'TbCar',
    default_color_icon: '',
    path: "/admin/traffic-volume",
    path_active: "/admin/traffic-volume",
    path_list: [],
  },
  {
    key: '4',
    title: 'Incident Detection',
    label: 'Incident Detection',
    label_key: "incident_detection",
    icon: 'TbCarCrash',
    default_color_icon: '',
    path: "/admin/incident-detection",
    path_active: "/admin/incident-detection",
    path_list: [],
  },
  {
    key: '5',
    title: 'Traffic Signal',
    label: 'Traffic Signal',
    label_key: "traffic_signal",
    icon: 'TbTrafficLights',
    default_color_icon: '',
    path: "/admin/traffic-signal",
    path_active: "/admin/traffic-signal",
    path_list: [],
  },
  {
    key: '6',
    title: 'Crosswalk',
    label: 'Crosswalk',
    label_key: "crosswalk",
    icon: "TbWalk",
    default_color_icon: '',
    path: "/admin/crosswalk",
    path_active: "/admin/crosswalk",
    path_list: [],
  },
  {
    key: '7',
    title: 'Traffic Lighting',
    label: 'Traffic Lighting',
    label_key: "traffic_lighting",
    icon: "TbBolt",
    default_color_icon: '',
    path: "/admin/traffic-lighting",
    path_active: "/admin/traffic-lighting",
    path_list: [],
  },
  {
    key: '8',
    title: 'VMS',
    label: "VMS",
    label_key: "vms",
    icon: "TbDeviceDesktop",
    default_color_icon: '',
    path: "/admin/vms",
    path_active: "/admin/vms",
    path_list: [],
  },
  {
    key: '9',
    title: 'Bridge Lighting',
    label: 'Bridge Lighting',
    label_key: "bridge_lighting",
    icon: "TbBuildingBridge",
    default_color_icon: '',
    path: "/admin/bridge-lighting",
    path_active: "/admin/bridge-lighting",
    path_list: [],
  },
  {
    key: '10',
    title: 'Tunnel',
    label: 'Tunnel',
    label_key: "tunnel",
    icon: "TbBuildingBridge2",
    default_color_icon: '',
    path: "/admin/tunnel",
    path_active: "/admin/tunnel",
    path_list: [],
  },
  {
    key: '11',
    title: 'Tracking',
    label: "Tracking",
    label_key: "tracking",
    icon: "",
    default_color_icon: '',
    path: "/admin/tracking",
    path_active: "/admin/tracking",
    path_list: [],
  },
  // SETTING
  {
    key: '12',
    title: 'Control VMS',
    label: "Control VMS",
    label_key: "control_vms",
    icon: "TbAdjustmentsHorizontal",
    default_color_icon: '',
    path: "/admin/control-vms",
    path_active: "/admin/control-vms",
    path_list: [],
  },
  {
    key: '13',
    title: 'Statistic',
    label: "Statistic",
    label_key: "statistic",
    icon: "TbChartColumn",
    default_color_icon: '',
    path: "/admin/statistics",
    path_active: "/admin/statistics",
    path_list: [],
  },
  {
    key: '14',
    title: 'Maintenance',
    label: "Maintenance",
    label_key: "maintenance",
    icon: "TbShieldHalf",
    default_color_icon: '',
    path: "/admin/maintenance",
    path_active: "/admin/maintenance",
    path_list: [],
  },
  // MANAGEMENT
  {
    key: '15',
    title: 'จัดการโครงการ',
    label: "จัดการโครงการ",
    label_key: "project_management",
    icon: "TbSettings",
    default_color_icon: '',
    path: "/admin/manage/project",
    path_active: "/admin/manage/project",
    path_list: [],
  },
  {
    key: '16',
    title: 'จัดการผู้รับจ้าง',
    label: "จัดการผู้รับจ้าง",
    label_key: "contact_management",
    icon: "TbUserSquare",
    default_color_icon: '',
    path: "/admin/manage/contact",
    path_active: "/admin/manage/contact",
    path_list: [],
  },
  {
    key: '17',
    title: 'จัดการสายทาง',
    label: "จัดการสายทาง",
    label_key: "route_management",
    icon: "TbMapPin",
    default_color_icon: '',
    path: "/admin/manage/route",
    path_active: "/admin/manage/route",
    path_list: [],
  },
  {
    key: '18',
    title: 'จัดการผู้ใช้งาน',
    label: "จัดการผู้ใช้งาน",
    label_key: "user_management",
    icon: "TbUser",
    default_color_icon: '',
    path: "/admin/manage/user",
    path_active: "/admin/manage/user",
    path_list: [],
  },
]

export default admin