// Barrel for Incident Detection (/analytic) query hooks.
export { incidentKeys } from './queryKeys'
export { useIncidentOverview } from './useIncidentOverview'
export { useIncidentTotals } from './useIncidentTotals'
export { useIncidentCentralTotals } from './useIncidentCentralTotals'
export { useIncidentCentralList } from './useIncidentCentralList'
export { useIncidentSolutionCameras } from './useIncidentSolutionCameras'
export { useIncidentRandomOnline } from './useIncidentRandomOnline'
export { useIncidentLicense } from './useIncidentLicense'
export { useIncidentCameraList } from './useIncidentCameraList'
export { useIncidentCameraTotals } from './useIncidentCameraTotals'
export { useIncidentDaily } from './useIncidentDaily'
export { useIncidentTransactions } from './useIncidentTransactions'
export { useIncidentDashboard } from './useIncidentDashboard'
export { useIncidentSolutionDetail } from './useIncidentSolutionDetail'
