export { default as StatisticsMapPanel } from './StatisticsMapPanel'
export { default as StatisticsComparisonTable } from './StatisticsComparisonTable'
export { default as DrawerMapSearchCard } from './DrawerMapSearchCard'
export type { StatisticsMapPanelProps, StatCard } from './StatisticsMapPanel'
export type { StatisticsComparisonTableProps, ComparisonRecord, SummaryBadge } from './StatisticsComparisonTable'
